### ISSUE TITLE
Wipe out database 

### ISSUE THREAD

**Issue by rafaelcastrocouto** [matthewfl/node-host#27]
Is there an API to erase all data-base????

I found `db.set`, `db.get`, `db.has` and `db.remove` ... there is no `db.clear`...

How can I reset a database? Plz help me Matthew!

**Comment by matthewfl** [comment]
just delete the db file?

**Comment by rafaelcastrocouto** [comment]
Thx for the reply, but how can I access the db file in jsapp.us? 
It does not show with the command "files".

**Comment by matthewfl** [comment]
sorry, I assumed you were running it locally, I don't believe there is a way to delete the database for an application once it is running.

**Comment by rafaelcastrocouto** [comment]
then I assume old data will be deleted if the db size reach some point...

2014-09-19 0:20 GMT-03:00 Matthew Francis-Landau notifications@github.com:

> sorry, I assumed you were running it locally, I don't believe there is a
> way to delete the database for an application once it is running.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matthewfl/node-host/issues/27#issuecomment-56131048.

## 

Rafael Castro do Couto
http://scriptogr.am/rafaelcastrocouto

**Comment by matthewfl** [comment]
? the db isn't going to be deleted

**Comment by rafaelcastrocouto** [comment]
Ok so I guess this can be closed ... 
(PS: Is jsapp down for good?)

**Comment by matthewfl** [comment]
@rafaelcastrocouto it isn't down for good, I just didn't notice that the server had stopped for some reason.

if you haven't noticed I am not really focusing on jsapp that much any more, eg it is still on an old version of nodejs and the node api that it is mocking hasn't really been updated.  Also there are loads of alternate nodejs hosting providers and vc backed companies attacking this problem, which wasn't true when jsapp was created.

**Comment by rafaelcastrocouto** [comment]
Yeah I know .. just uploaded my project to heroku, but I must admit I prefer jsapp aproach!  

 =D
