### ISSUE TITLE
Cannot change profile image

### ISSUE THREAD

**Issue by kevin212** [matthewfl/node-host#29]
I just created a profile at http://jsapp.us, but I notice that a generic image is used:

http://www.gravatar.com/avatar/1e5e1048e7215903c4224f58dde04997?d=identicon&s=200

How can I edit that setting so that an actual photo of me is used?

Thanks,

Kevin

**Comment by matthewfl** [comment]
you can make an account on gravatar using the email address you registered with and that will change the image served by gravatar.

eg: http://www.gravatar.com/avatar/614fee2a7d5b30f5eebb22a45dc8ad7e?d=identicon&s=200
